-- Every table the CRM uses, as they exist on the original deployment.
-- One time: paste this whole file into the Supabase SQL editor and run it.
-- Safe to run again: everything is "if not exists".
-- Row level security is on for every table; the CRM reads and writes with
-- the service key only, so nothing here is reachable with the public key.

create table if not exists public.activities (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  occurred_at timestamp with time zone default now() not null,
  lead_row integer,
  lead_email text,
  business text,
  channel text not null,
  kind text,
  step integer,
  subject text,
  preview text,
  provider text,
  external_id text,
  source text,
  done_by text,
  data jsonb,
  constraint activities_channel_check CHECK ((channel = ANY (ARRAY['email'::text, 'call'::text, 'dm'::text, 'sms'::text, 'note'::text, 'status'::text, 'proposal'::text, 'payment'::text, 'click'::text]))),
  constraint activities_pkey PRIMARY KEY (id)
);
create index if not exists activities_lead_email_idx ON public.activities USING btree (lower(lead_email));
create index if not exists activities_lead_row_idx ON public.activities USING btree (lead_row);
create index if not exists activities_occurred_idx ON public.activities USING btree (occurred_at DESC);
create unique index if not exists activities_provider_external_idx ON public.activities USING btree (provider, external_id);
alter table public.activities enable row level security;

create table if not exists public.deals (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  closed_on date default CURRENT_DATE not null,
  business text not null,
  email text,
  lead_row integer,
  amount numeric not null,
  currency text default 'GBP'::text not null,
  source text,
  notes text,
  mrr numeric default 0 not null,
  constraint deals_amount_check CHECK ((amount >= (0)::numeric)),
    phone text,
constraint deals_pkey PRIMARY KEY (id)
);
create index if not exists deals_closed_on_idx ON public.deals USING btree (closed_on DESC);
alter table public.deals enable row level security;

create table if not exists public.email_events (
  id bigint generated by default as identity not null,
  provider_id text not null,
  event text not null,
  occurred_at timestamp with time zone default now() not null,
  to_email text,
  sender text,
  sending_domain text,
  raw jsonb,
  created_at timestamp with time zone default now() not null,
  constraint email_events_pkey PRIMARY KEY (id)
);
create index if not exists email_events_provider_idx ON public.email_events USING btree (provider_id);
create index if not exists email_events_domain_idx ON public.email_events USING btree (sending_domain, event);
create unique index if not exists email_events_unique ON public.email_events USING btree (provider_id, event, occurred_at);
alter table public.email_events enable row level security;

create table if not exists public.emails (
  id bigint generated by default as identity not null,
  slug text,
  business text not null,
  to_email text not null,
  subject text not null,
  body_html text,
  body_text text,
  site_url text,
  proposal_url text,
  status text default 'queued'::text not null,
  provider_id text,
  error text,
  sent_at timestamp with time zone default now() not null,
  sender text,
  constraint emails_pkey PRIMARY KEY (id)
);
create index if not exists emails_sent_at_idx ON public.emails USING btree (sent_at DESC);
create index if not exists emails_sender_day_idx ON public.emails USING btree (sender, sent_at DESC);
alter table public.emails enable row level security;

-- Where every "Could not ..." toast reports itself (Today's "Needs attention" card).
create table if not exists public.failures (
  id bigint generated by default as identity primary key,
  occurred_at timestamp with time zone default now() not null,
  place text not null,
  message text not null,
  detail jsonb
);
create index if not exists failures_occurred_at_idx ON public.failures USING btree (occurred_at DESC);
alter table public.failures enable row level security;

-- The short code on a found lead's tracked link. Defined before the table
-- that uses it as a default; the body only reads the table at call time.
create or replace function public.new_lead_code()
 returns text
 language plpgsql
as $function$
declare
  alphabet text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  code text;
  i int;
begin
  loop
    code := '';
    for i in 1..6 loop
      code := code || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    -- Vanishingly unlikely at 32^6, but checked rather than assumed.
    exit when not exists (select 1 from public.found_leads where lead_code = code);
  end loop;
  return code;
end;
$function$;

create table if not exists public.found_leads (
  slug text not null,
  business text not null,
  category text,
  city text,
  address text,
  phone text,
  email text,
  website text,
  rating numeric,
  reviews integer,
  google_maps_url text,
  site_url text,
  proposal_url text,
  subject text,
  email_body text,
  emailed boolean default false,
  found_at timestamp with time zone default now() not null,
  facebook text,
  instagram text,
  linkedin text,
  website_status text,
  short_message text,
  lead_code text default new_lead_code(),
  constraint found_leads_pkey PRIMARY KEY (slug)
);
create index if not exists found_leads_when ON public.found_leads USING btree (found_at DESC);
create unique index if not exists found_leads_code_idx ON public.found_leads USING btree (lead_code);
alter table public.found_leads enable row level security;

-- Small settings with no table of their own (the referral terms).
create table if not exists public.kv (
  key text not null,
  value jsonb default '{}'::jsonb not null,
  updated_at timestamp with time zone default now() not null,
  constraint kv_pkey PRIMARY KEY (key)
);
alter table public.kv enable row level security;

create table if not exists public.lead_edits (
  key text not null,
  lead_row integer,
  fields jsonb default '{}'::jsonb not null,
  deleted boolean default false not null,
  added boolean default false not null,
  updated_at timestamp with time zone default now() not null,
  constraint lead_edits_pkey PRIMARY KEY (key)
);
alter table public.lead_edits enable row level security;

-- The local lead book. Ids are the old sheet row numbers, so activities,
-- tasks and deals that point at a lead by row keep pointing at the same lead.
-- A copy with no sheet URL starts here, empty; a copy still on a sheet moves
-- over the moment this table has a row (see api/_leads.js).
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  track text default 'local' not null,
  source text default 'scraper' not null,
  deleted boolean default false not null,
  business text,
  owner_name text,
  phone text,
  email text,
  why text,
  website text,
  facebook text,
  instagram text,
  heat text,
  website_status text,
  category text,
  rating text,
  reviews text,
  address text,
  city text,
  region text,
  postal_code text,
  country text,
  google_maps_url text,
  status text default 'New' not null,
  contacted_on text,
  notes text,
  assigned_to text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);
create index if not exists leads_email_idx ON public.leads USING btree (lower(email)) WHERE (deleted = false);
create index if not exists leads_name_town_idx ON public.leads USING btree (lower(business), lower(city)) WHERE (deleted = false);
alter table public.leads enable row level security;

create table if not exists public.outreach_settings (
  sender_key text not null,
  label text,
  enabled boolean default true not null,
  daily_cap integer default 100 not null,
  warm_start date,
  updated_at timestamp with time zone default now() not null,
  constraint outreach_settings_pkey PRIMARY KEY (sender_key)
);
alter table public.outreach_settings enable row level security;

create table if not exists public.profile (
  id integer default 1 not null,
  name text,
  business text,
  phone text,
  sender_from text,
  video_link text,
  website text,
  timezone text,
  currency text default 'GBP'::text,
  links jsonb,
  -- The operator's photo, stored inline as a data URL. A 256px square JPEG is
  -- around 20KB, so no storage bucket and no second request to draw a face.
  avatar text,
  -- Name and role for each email on allowed_emails. Supabase Auth holds the
  -- login itself; this is the part a person reads on the Team page.
  team jsonb,
  updated_at timestamp with time zone default now() not null,
  digest jsonb,
  ai jsonb,
  constraint profile_id_check CHECK ((id = 1)),
  constraint profile_pkey PRIMARY KEY (id)
);
alter table public.profile enable row level security;

create table if not exists public.referrals (
  id bigint generated by default as identity not null,
  date date default CURRENT_DATE not null,
  customer text not null,
  customer_email text default ''::text not null,
  customer_phone text default ''::text not null,
  job text default ''::text not null,
  referrer text not null,
  referrer_email text default ''::text not null,
  reward numeric default 0 not null,
  reward_type text default 'cash'::text not null,
  status text default 'Pending'::text not null,
  paid_on date,
  payment_ref text default ''::text not null,
  created_at timestamp with time zone default now() not null,
  track text default 'local'::text not null,
  constraint referrals_pkey PRIMARY KEY (id)
);
alter table public.referrals enable row level security;

create table if not exists public.saved_views (
  id bigint generated by default as identity not null,
  name text not null,
  filters jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint saved_views_pkey PRIMARY KEY (id)
);
alter table public.saved_views enable row level security;

-- Before sequence_runs: its rows point at these.
create table if not exists public.sequences (
  id bigint generated by default as identity not null,
  name text not null,
  steps jsonb default '[]'::jsonb not null,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  constraint sequences_pkey PRIMARY KEY (id)
);
alter table public.sequences enable row level security;

create table if not exists public.sequence_runs (
  id bigint generated by default as identity not null,
  sequence_id bigint not null,
  lead_row integer,
  business text not null,
  email text,
  phone text,
  slug text,
  step_index integer default 0 not null,
  next_due date,
  status text default 'active'::text not null,
  stopped_reason text,
  started_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  town text,
  constraint sequence_runs_pkey PRIMARY KEY (id),
  constraint sequence_runs_sequence_id_fkey FOREIGN KEY (sequence_id) REFERENCES sequences(id) ON DELETE CASCADE
);
create index if not exists seqrun_due_idx ON public.sequence_runs USING btree (status, next_due);
create unique index if not exists seqrun_once_idx ON public.sequence_runs USING btree (sequence_id, lead_row) WHERE (lead_row IS NOT NULL);
alter table public.sequence_runs enable row level security;

create table if not exists public.sheet_cache (
  key text not null,
  payload jsonb not null,
  saved_at timestamp with time zone default now() not null,
  constraint sheet_cache_pkey PRIMARY KEY (key)
);
alter table public.sheet_cache enable row level security;

create table if not exists public.sites (
  slug text not null,
  business text not null,
  config jsonb not null,
  email text,
  emailed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  constraint sites_pkey PRIMARY KEY (slug)
);

-- A built site, its proposal page and the template kit read the site's config
-- with the public anon key, so that one policy is the only public door in the
-- database: reading, and only the three columns a visitor of that site could
-- see anyway. The lead's email on the row stays out of reach of the public key.
revoke all on public.sites from anon;
grant select (slug, business, config) on public.sites to anon;
drop policy if exists sites_public_read on public.sites;
create policy sites_public_read on public.sites for select to anon using (true);
alter table public.sites enable row level security;

create table if not exists public.tasks (
  id bigint generated by default as identity not null,
  lead_row integer,
  business text not null,
  title text not null,
  kind text default 'follow_up'::text not null,
  due_on date not null,
  done boolean default false not null,
  done_at timestamp with time zone,
  note text,
  created_at timestamp with time zone default now() not null,
  constraint tasks_pkey PRIMARY KEY (id)
);
create index if not exists tasks_due_idx ON public.tasks USING btree (done, due_on);
create index if not exists tasks_lead_idx ON public.tasks USING btree (lead_row);
alter table public.tasks enable row level security;

create table if not exists public.templates (
  id bigint generated by default as identity not null,
  name text not null,
  subject text default ''::text not null,
  body text default ''::text not null,
  created_at timestamp with time zone default now() not null,
  constraint templates_pkey PRIMARY KEY (id)
);
alter table public.templates enable row level security;

create table if not exists public.scripts (
  id bigint generated by default as identity not null,
  channel text not null,
  key text,
  title text not null,
  situation text default ''::text not null,
  subject text default ''::text not null,
  body text not null,
  sort integer default 100 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint scripts_pkey PRIMARY KEY (id),
  constraint scripts_channel_check CHECK ((channel = ANY (ARRAY['email'::text, 'call'::text, 'dm'::text, 'sales'::text])))
);
alter table public.scripts enable row level security;

alter table public.sequence_runs add column if not exists trade text;

-- The session epoch, bumped to sign every other device out. _auth.js reads and
-- writes it, and it was missing here, so a fresh install got a profile table
-- without it and "Sign out everywhere" answered 502.
alter table public.profile add column if not exists session_epoch integer default 0;

-- Who may sign in, on top of CRM_USERS: written when a login is made in Settings, You.
alter table public.profile add column if not exists allowed_emails jsonb default '[]'::jsonb;

-- The key outside software calls this CRM with, written when Settings rotates
-- it. It lives here rather than only in ACTIVITY_SECRET because a running
-- deployment cannot read a Vercel variable back to a screen and cannot change
-- one, so Settings had no key to show and no way to replace a leaked one.
-- api/activity.js and api/log.js accept this key or the variable, so an install
-- that never rotates keeps working on the variable alone.
alter table public.profile add column if not exists api_key text;

-- Replies (2026-09-14). reply_to is the address a prospect's answer comes back
-- to, which is rarely the address the mail went out from; it was the
-- RESEND_REPLY_TO variable, so changing your own inbox meant a redeploy.
-- inbound_secret is the signing secret Resend hands out for the webhook that
-- points at /api/inbound: every delivery is signed with it, and without one
-- that endpoint refuses everything rather than trusting a POST it cannot check.
-- Both are here for the same reason api_key is, and missing them does more than
-- turn replies off: api/profile.js writes reply_to on every save from Settings,
-- so a fresh install without these columns cannot save a profile at all.
alter table public.profile add column if not exists reply_to text;
alter table public.profile add column if not exists inbound_secret text;

-- ---------------------------------------------------------------------------
-- Two books of business: local businesses and online coaches (2026-09-12)
--
-- One database, one column. Every row belongs to exactly one track, and the
-- data layer filters on it in a single place, so the two can never show each
-- other's leads, money or activity. Existing rows default to 'local' because
-- that is all the CRM has ever held, which makes this migration a no-op for
-- anyone already running it.
--
-- Deliberately NOT tracked: profile (one person, one identity),
-- outreach_settings (sending caps belong to the mailbox, not the book),
-- lead_edits (it overlays Google Sheet rows, which are local by definition),
-- found_leads and sheet_cache (both part of the local scrape path).
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'deals','activities','tasks',
    'sequences','sequence_runs','emails','email_events',
    'scripts','saved_views',
    'templates','sites'
  ] loop
    if exists (select 1 from information_schema.tables
               where table_schema='public' and table_name=t) then
      execute format('alter table public.%I add column if not exists track text not null default ''local''', t);
      execute format('create index if not exists %I on public.%I (track)', t||'_track_idx', t);
    end if;
  end loop;
end $$;

-- Online coach leads. A coach is added by pasting a profile URL or a username,
-- so this table has none of the Google Maps shape (no address, trade, rating).
-- It is a separate table rather than a tracked one because local leads live in
-- the Google Sheet, not here: the two lead stores were never one thing.
create table if not exists public.coach_leads (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  handle text not null,
  platform text default 'instagram' not null,
  profile_url text,
  name text,
  business text,
  niche text,
  followers integer,
  email text,
  phone text,
  website text,
  heat text default 'WARM' not null,
  status text default 'New' not null,
  notes text,
  lead_code text,
  deleted boolean default false not null,
  assigned_to text,
  constraint coach_leads_pkey PRIMARY KEY (id),
  constraint coach_leads_platform_check CHECK ((platform = ANY (ARRAY['instagram'::text,'youtube'::text,'tiktok'::text,'x'::text,'linkedin'::text,'facebook'::text,'other'::text])))
);
alter table public.coach_leads enable row level security;
create unique index if not exists coach_leads_handle_idx on public.coach_leads (lower(handle), platform) where deleted = false;

-- The dedupe index needs the track in it. Unique on (provider, external_id)
-- alone meant a coach webhook reusing an id the local book already held was
-- silently dropped as a duplicate: not a leak, but a lost write.
--
-- No WHERE clause, deliberately. Postgres will not accept a PARTIAL unique
-- index as an ON CONFLICT target, and both writers (api/activity.js and
-- api/go.js) upsert against this index. While it was partial every insert
-- was refused: logging a call or a DM answered "Could not log that
-- activity", and link-open tracking failed silently. A plain unique index
-- behaves the same way here anyway, because nulls are distinct, so rows with
-- no provider or no external_id still never collide.
drop index if exists activities_provider_external_idx;
drop index if exists activities_provider_external_track_idx;
create unique index if not exists activities_provider_external_track_idx
  on public.activities (provider, external_id, track);

-- Sample data (Settings, Data): every made-up row carries sample = true so
-- one delete removes them all and never touches a real lead. Idempotent.
do $$ declare t text; begin
  foreach t in array array['leads','coach_leads','activities','deals','tasks','referrals'] loop
    execute format('alter table public.%I add column if not exists sample boolean not null default false', t);
  end loop;
end $$;

-- Snooze (a lead hidden from the list and the runs until a day) and targets
-- (daily and weekly, per book, on the profile). Idempotent.
do $$ declare t text; begin
  foreach t in array array['leads','coach_leads'] loop
    execute format('alter table public.%I add column if not exists snooze_until date', t);
  end loop;
  foreach t in array array['profile'] loop
    execute format('alter table public.%I add column if not exists targets jsonb', t);
  end loop;
end $$;

-- Scripts: what a DM script is used for (open, pivot, bump, chase, no) and
-- whether it is a favourite (rises to the top, used first). Idempotent.
do $$ declare t text; begin
  foreach t in array array['scripts'] loop
    execute format('alter table public.%I add column if not exists use text not null default %L', t, '');
    execute format('alter table public.%I add column if not exists favourite boolean not null default false', t);
  end loop;
end $$;